language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2.1-003177
mono:
  - latest
os:
  - linux
node_js:
  - '6.9.1'
before_install:
  - npm install compare-obj diff fs path child_process
  - npm install -g z-schema
install:
  - nvm install 6.9.1
  - nvm use 6.9.1
  - sh script/setup.sh
  - sh script/cibuild.sh
  - sh script/linters.sh
script:
#  - node test/integration.js
